name: Deploy

concurrency:
  group: deploy

on:
  workflow_dispatch

jobs:
  build-tgui:
    name: Build TGUI js
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies and build
        run: |
          cd ./tgui
          yarn install
          yarn run build
